Fixed Gemfile to permit development with local Logstash clone
logstash-plugins/logstash-input-azure_event_hubs pull request #82
Opened 2023-05-18 13:42 UTC by andsel

## Release notes

[rn:skip]

## What does this PR do?

Fix the `Gemfile` to properly set variables to use local Logstash clone

## Why is it important/What is the impact to the user?

Let the developer to use local clone, when configuring `LOGSTASH_PATH` and `LOGSTASH_SOURCE` instead of raising `java.lang.NoClassDefFoundError`

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## How to test this PR locally

Follow instruction in #81 

## Related issues
- Fixes #81

## Use cases

## Screenshots

## Logs

2023-05-30 15:09 UTC, roaksoax commented on Gemfile
> +logstash_path = ENV['LOGSTASH_PATH'] || 'path/to/local/logstash'
Shouldn't this be something like:

`ENV['LOGSTASH_PATH'] || '../../logstash'`

What I'm reading here is that before this change, when running the tests WITH or WITHOUT the variable, it will look for logstash under `../../logstash`.  However, after making this change, it will only work IF you set a value for LOGSTASH_PATH.

So that, before the change, the following would work:

> export LOGSTASH_SOURCE=1
> bundle install
> bundle exec rspec

After the change, it would not work because LOGSTASH_PATH is not passed as an env variable.

So basically, the solution should be that IF `LOGSTASH_PATH` is not passed, it should fallback to `../../logstash`

2023-05-30 15:14 UTC, roaksoax commented on Gemfile
> +if Dir.exist?(logstash_path) && use_logstash_source
I don't think use_logstash_source is really needed, because of my previous comment.

2023-05-30 15:15 UTC, roaksoax requested changes

2023-05-30 15:15 UTC, roaksoax commented on Gemfile
> +
There's no reason to add 3 empty lines here.

2023-05-31 09:29 UTC, andsel commented on Gemfile
> +if Dir.exist?(logstash_path) && use_logstash_source
It's the same like in Beats input: https://github.com/logstash-plugins/logstash-input-beats/blob/main/Gemfile#L8

2023-05-31 14:23 UTC, roaksoax approved these changes
Approving, but before landing consider my last comment provided that it is not necessary to make the change you are suggesting.

2023-05-31 14:23 UTC, roaksoax commented on Gemfile
> +if Dir.exist?(logstash_path) && use_logstash_source
While it may be, I still don't think it is a necessary change.

Example 1: In this code, you are setting use_logstash_source to 1 if LOGSTASH_SOURCE is equal to 1.
```
use_logstash_source = ENV['LOGSTASH_SOURCE'] && ENV['LOGSTASH_SOURCE'].to_s == '1'
if Dir.exist?(logstash_path) && use_logstash_source
```

Example 2: The above is the same as the following code, which is evaluating if LOGSTASH_SOURCE is equal to 1.
```
if Dir.exist?(logstash_path) && ENV["LOGSTASH_SOURCE"] == "1"
```

Meaning that the change is not really necessary.

2023-05-31 15:15 UTC, andsel commented on Gemfile
> +if Dir.exist?(logstash_path) && use_logstash_source
Yes you are right, 
```sh
ENV['LOGSTASH_SOURCE'] && ENV['LOGSTASH_SOURCE'].to_s == '1'
```

provides the same result as 

```sh
ENV['LOGSTASH_SOURCE'] == '1'
```

but my point here is to use the exact `Gemfile` that's used in all the other plugins. If we change here should we align also the others?

2023-06-01 07:45 UTC, merged